# Generated by Django 3.1.2 on 2020-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('pw', models.TextField(default=None)),
                ('sub', models.TextField(default=None)),
                ('mobile', models.BigIntegerField(default=0)),
            ],
        ),
    ]
